# Generated by Django 3.2.6 on 2021-08-06 08:59

import api.films.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Genre title')),
                ('description', models.TextField(max_length=1500, verbose_name='Genre description')),
            ],
            options={
                'verbose_name': 'Film Genre',
                'verbose_name_plural': 'Films Genres',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_image', models.ImageField(upload_to=api.films.models.film_title_image_upload_path)),
                ('title', models.CharField(max_length=150, verbose_name='Film title')),
                ('description', models.TextField(max_length=150, verbose_name='Film title')),
                ('genres', models.ManyToManyField(related_name='film_genres', to='films.FilmGenre', verbose_name='Film genres')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
            },
        ),
    ]
