# Generated by Django 3.2.6 on 2021-08-06 09:44

import api.apps.films.models
import autoslug.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_image', models.ImageField(upload_to=api.apps.films.models.film_title_image_upload_path, verbose_name='Film image')),
                ('title', models.CharField(max_length=150, verbose_name='Film title')),
                ('description', models.TextField(max_length=150, verbose_name='Film description')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='Film duration')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Film slug')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
            },
        ),
        migrations.CreateModel(
            name='FilmActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Actor`s image')),
                ('first_name', models.CharField(max_length=100, verbose_name='Actor`s first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Actor`s last name')),
                ('birth_date', models.DateField(verbose_name='Actor`s birth date')),
            ],
            options={
                'verbose_name': 'Film actor',
                'verbose_name_plural': 'Films actors',
            },
        ),
        migrations.CreateModel(
            name='FilmGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Genre title')),
                ('description', models.TextField(max_length=1500, verbose_name='Genre description')),
            ],
            options={
                'verbose_name': 'Film Genre',
                'verbose_name_plural': 'Films Genres',
            },
        ),
        migrations.CreateModel(
            name='FilmManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Film manufacturer title')),
                ('country', models.CharField(max_length=150, verbose_name='Manufacturer country')),
            ],
        ),
        migrations.CreateModel(
            name='FilmImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.apps.films.models.film_additional_image_upload_path, verbose_name='Film image')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Image description')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_film_image', to='films.film', verbose_name='Image film')),
            ],
            options={
                'verbose_name': 'Film image',
                'verbose_name_plural': 'Films images',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(related_name='film_actors', to='films.FilmActor', verbose_name='Film actors'),
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(related_name='film_genres', to='films.FilmGenre', verbose_name='Film genres'),
        ),
        migrations.AddField(
            model_name='film',
            name='manufacturer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='films.filmmanufacturer', verbose_name='Film manufacturer'),
        ),
    ]
